documentation:
- changed-files:
  - any-glob-to-any-file: '**/*.md'

posters:
- changed-files:
  - any-glob-to-any-file: 
    - 'BepInEx/plugins/LethalPaintings/paintings/*.png'
    - 'BepInEx/plugins/LethalPosters/posters/*.png'
    - 'BepInEx/plugins/LethalPosters/tips/*.png'

cicd:
- changed-files:
  - any-glob-to-any-file: 
    - '.github/**'