documentation:
- changed-files:
  - any-glob-to-any-file: '**/*.md'

posters:
- changed-files:
  - any-glob-to-any-file: 
    - 'BepInEx/plugins/BikininjasPosters*/posters/**'
    - 'BepInEx/plugins/BikininjasPosters*/tips/**'

cicd:
- changed-files:
  - any-glob-to-any-file: 
    - '.github/**'