name: Publish Package on Thunderstore

on:
  workflow_dispatch:
  release:
    types: [released]

env:
  description: "Bikininjas Custom Posters with french people and memes for Lethal Company"
  mod_name: "BikininjasCustomPosters"
  website_url: "https://github.com/${{ github.repository }}"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          
      - name: Get latest release version
        id: get_version
        uses: actions/github-script@v7
        with:
          script: |
            const { data: release } = await github.rest.repos.getLatestRelease({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            core.setOutput('version', release.tag_name);
            console.log(`Latest release version: ${release.tag_name}`);

      - name: Upload to Thunderstore
        uses: GreenTF/upload-thunderstore-package@v4.3
        with:
          namespace: Bikininjas
          description: ${{ env.description }}
          token: ${{ secrets.THUNDERSTORE_SVC_API_KEY }}
          name: ${{ env.mod_name }}
          version: ${{ steps.get_version.outputs.version }}
          community: lethal-company
          deps: |
            seechela-CustomPosters-3.2.0
          website: ${{ env.website_url }}
          repo: thunderstore.io
          categories: |
            posters